server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 192.168.11.134:22122

ly:
  upload:
    baseurl: http://image.leyou.com/
    allowTypes:
      - image/png
      - image/jpeg


