server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    username: root
    password: 123456
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&characterEncoding=utf-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


